name: black check and flake8
on: [push]
jobs:
  install-packages:
    name: install-packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: install requirements
        run: pip install -r requirements.txt
      - name: Flake8 linting
        run: flake8 aoc --max-line-length=88 --extend-ignore=E203
      - name: Black linting
        run: black --check aoc
